import type { Achievement } from '../types';

export const ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first_problem',
    title: 'First Blood',
    description: 'Solve your first problem',
    icon: '⚔️',
    xpReward: 100,
    condition: (s) => s.solvedProblems >= 1,
  },
  {
    id: 'first_pattern',
    title: 'Pattern Seeker',
    description: 'Complete your first pattern',
    icon: '🔍',
    xpReward: 250,
    condition: (s) => s.completedPatterns >= 1,
  },
  {
    id: 'first_world',
    title: 'World Conqueror',
    description: 'Complete your first world',
    icon: '🌍',
    xpReward: 500,
    condition: (s) => s.completedWorlds >= 1,
  },
  {
    id: 'streak_7',
    title: 'Week Warrior',
    description: 'Maintain a 7-day streak',
    icon: '🔥',
    xpReward: 350,
    condition: (s) => s.streak >= 7,
  },
  {
    id: 'streak_30',
    title: 'Month Master',
    description: 'Maintain a 30-day streak',
    icon: '🌟',
    xpReward: 1500,
    condition: (s) => s.streak >= 30,
  },
  {
    id: 'streak_100',
    title: 'Unstoppable',
    description: 'Maintain a 100-day streak',
    icon: '💎',
    xpReward: 5000,
    condition: (s) => s.streak >= 100,
  },
  {
    id: 'problems_10',
    title: 'Getting Started',
    description: 'Solve 10 problems',
    icon: '🎯',
    xpReward: 200,
    condition: (s) => s.solvedProblems >= 10,
  },
  {
    id: 'problems_50',
    title: 'Problem Hunter',
    description: 'Solve 50 problems',
    icon: '🏹',
    xpReward: 750,
    condition: (s) => s.solvedProblems >= 50,
  },
  {
    id: 'problems_100',
    title: 'Century Slayer',
    description: 'Solve 100 problems',
    icon: '💯',
    xpReward: 2000,
    condition: (s) => s.solvedProblems >= 100,
  },
  {
    id: 'problems_500',
    title: 'Problem God',
    description: 'Solve 500 problems',
    icon: '🏆',
    xpReward: 10000,
    condition: (s) => s.solvedProblems >= 500,
  },
  {
    id: 'worlds_5',
    title: 'Explorer',
    description: 'Complete 5 worlds',
    icon: '🗺️',
    xpReward: 1000,
    condition: (s) => s.completedWorlds >= 5,
  },
  {
    id: 'worlds_10',
    title: 'World Traveler',
    description: 'Complete 10 worlds',
    icon: '✈️',
    xpReward: 3000,
    condition: (s) => s.completedWorlds >= 10,
  },
  {
    id: 'worlds_all',
    title: 'DSA Grandmaster',
    description: 'Complete all 21 worlds',
    icon: '👑',
    xpReward: 20000,
    condition: (s) => s.completedWorlds >= 21,
  },
  {
    id: 'level_10',
    title: 'Rising Star',
    description: 'Reach Level 10',
    icon: '⭐',
    xpReward: 500,
    condition: (s) => s.level >= 10,
  },
  {
    id: 'level_25',
    title: 'Veteran Coder',
    description: 'Reach Level 25',
    icon: '🌠',
    xpReward: 2000,
    condition: (s) => s.level >= 25,
  },
  {
    id: 'level_50',
    title: 'Algorithm Emperor',
    description: 'Reach Level 50',
    icon: '🔱',
    xpReward: 10000,
    condition: (s) => s.level >= 50,
  },
  {
    id: 'patterns_10',
    title: 'Pattern Master',
    description: 'Complete 10 patterns',
    icon: '🎨',
    xpReward: 1000,
    condition: (s) => s.completedPatterns >= 10,
  },
  {
    id: 'array_master',
    title: 'Array Master',
    description: 'Complete the Array Desert world',
    icon: '🏜️',
    xpReward: 1000,
    condition: (s) => s.completedWorlds >= 2,
  },
  {
    id: 'graph_king',
    title: 'Graph King',
    description: 'Complete the Graph Empire world',
    icon: '🗺️',
    xpReward: 3000,
    condition: (s) => s.completedWorlds >= 16,
  },
  {
    id: 'dp_slayer',
    title: 'DP Slayer',
    description: 'Complete the DP Galaxy world',
    icon: '🌌',
    xpReward: 5000,
    condition: (s) => s.completedWorlds >= 19,
  },
  // ── Spaced Repetition achievements ──────────────────────────────────
  {
    id: 'sr_first_review',
    title: 'First Recall',
    description: 'Complete your first spaced repetition review',
    icon: '🧠',
    xpReward: 100,
    condition: (s) => s.totalReviews >= 1,
  },
  {
    id: 'sr_reviews_10',
    title: 'Memory Forger',
    description: 'Complete 10 spaced repetition reviews',
    icon: '🔄',
    xpReward: 300,
    condition: (s) => s.totalReviews >= 10,
  },
  {
    id: 'sr_reviews_50',
    title: 'Memory Keeper',
    description: 'Complete 50 spaced repetition reviews',
    icon: '💡',
    xpReward: 750,
    condition: (s) => s.totalReviews >= 50,
  },
  {
    id: 'sr_reviews_200',
    title: 'Iron Recall',
    description: 'Complete 200 spaced repetition reviews',
    icon: '🏅',
    xpReward: 2500,
    condition: (s) => s.totalReviews >= 200,
  },
  {
    id: 'sr_reviews_500',
    title: 'Photographic Memory',
    description: 'Complete 500 spaced repetition reviews',
    icon: '🧬',
    xpReward: 7500,
    condition: (s) => s.totalReviews >= 500,
  },
];
