import type { World } from '../types';

export const WORLDS: World[] = [
  {
    id: 1,
    name: 'Beginner Forest',
    subtitle: 'Where legends begin',
    description: 'Master the fundamentals of programming and algorithmic thinking. Learn variables, loops, functions, and the language of complexity.',
    icon: '🌲',
    color: '#22c55e',
    bgGradient: 'from-green-900/40 to-emerald-800/20',
    boss: 'Complexity Guardian',
    bossDescription: 'A colossal tree spirit that tests your understanding of time and space complexity. Only those who can analyze Big O notation may pass.',
    position: { x: 15, y: 75 },
    patterns: [
      {
        id: 'w1-variables',
        name: 'Variables & Data Types',
        description: 'Foundation of all programs — understanding how data is stored and typed.',
        worldId: 1,
        problems: [
          { id: 'p1-1', title: 'Find the Largest Number', difficulty: 'easy', platform: 'LeetCode', pattern: 'Variables & Data Types', estimatedTime: 10, link: 'https://leetcode.com/problems/find-the-highest-altitude/', worldId: 1, patternId: 'w1-variables' },
          { id: 'p1-2', title: 'Running Sum of 1D Array', difficulty: 'easy', platform: 'LeetCode', pattern: 'Variables & Data Types', estimatedTime: 10, link: 'https://leetcode.com/problems/running-sum-of-1d-array/', worldId: 1, patternId: 'w1-variables' },
        ],
      },
      {
        id: 'w1-loops',
        name: 'Loops & Iteration',
        description: 'Control flow mastery — from simple loops to nested iteration patterns.',
        worldId: 1,
        problems: [
          { id: 'p1-3', title: 'FizzBuzz', difficulty: 'easy', platform: 'LeetCode', pattern: 'Loops & Iteration', estimatedTime: 10, link: 'https://leetcode.com/problems/fizz-buzz/', worldId: 1, patternId: 'w1-loops' },
          { id: 'p1-4', title: 'Count Odd Numbers in an Interval', difficulty: 'easy', platform: 'LeetCode', pattern: 'Loops & Iteration', estimatedTime: 15, link: 'https://leetcode.com/problems/count-odd-numbers-in-an-interval-range/', worldId: 1, patternId: 'w1-loops' },
        ],
      },
      {
        id: 'w1-functions',
        name: 'Functions & Recursion Basics',
        description: 'Writing reusable, modular code — the building blocks of complex algorithms.',
        worldId: 1,
        problems: [
          { id: 'p1-5', title: 'Power of Three', difficulty: 'easy', platform: 'LeetCode', pattern: 'Functions & Recursion Basics', estimatedTime: 15, link: 'https://leetcode.com/problems/power-of-three/', worldId: 1, patternId: 'w1-functions' },
          { id: 'p1-6', title: 'Fibonacci Number', difficulty: 'easy', platform: 'LeetCode', pattern: 'Functions & Recursion Basics', estimatedTime: 15, link: 'https://leetcode.com/problems/fibonacci-number/', worldId: 1, patternId: 'w1-functions' },
        ],
      },
      {
        id: 'w1-complexity',
        name: 'Time & Space Complexity',
        description: 'Learn to analyze algorithm efficiency using Big O notation.',
        worldId: 1,
        problems: [
          { id: 'p1-7', title: 'Two Sum', difficulty: 'easy', platform: 'LeetCode', pattern: 'Time & Space Complexity', estimatedTime: 20, link: 'https://leetcode.com/problems/two-sum/', worldId: 1, patternId: 'w1-complexity' },
          { id: 'p1-8', title: 'Contains Duplicate', difficulty: 'easy', platform: 'LeetCode', pattern: 'Time & Space Complexity', estimatedTime: 15, link: 'https://leetcode.com/problems/contains-duplicate/', worldId: 1, patternId: 'w1-complexity' },
          { id: 'p1-9', title: 'Majority Element', difficulty: 'medium', platform: 'LeetCode', pattern: 'Time & Space Complexity', estimatedTime: 25, link: 'https://leetcode.com/problems/majority-element/', worldId: 1, patternId: 'w1-complexity' },
        ],
      },
    ],
  },
  {
    id: 2,
    name: 'Array Desert',
    subtitle: 'Endless sands of data',
    description: 'Conquer the vast Array Desert. Learn every array manipulation technique and emerge as a true array warrior.',
    icon: '🏜️',
    color: '#f59e0b',
    bgGradient: 'from-yellow-900/40 to-amber-800/20',
    boss: 'Array King',
    bossDescription: 'An ancient colossus built from shifting sands and crystallized data. Master all array patterns to shatter its defenses.',
    position: { x: 28, y: 62 },
    patterns: [
      {
        id: 'w2-traversal',
        name: 'Array Traversal',
        description: 'Fundamental techniques for iterating through arrays efficiently.',
        worldId: 2,
        problems: [
          { id: 'p2-1', title: 'Best Time to Buy and Sell Stock', difficulty: 'easy', platform: 'LeetCode', pattern: 'Array Traversal', estimatedTime: 20, link: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/', worldId: 2, patternId: 'w2-traversal' },
          { id: 'p2-2', title: 'Maximum Subarray', difficulty: 'medium', platform: 'LeetCode', pattern: 'Array Traversal', estimatedTime: 25, link: 'https://leetcode.com/problems/maximum-subarray/', worldId: 2, patternId: 'w2-traversal' },
          { id: 'p2-3', title: 'Product of Array Except Self', difficulty: 'medium', platform: 'LeetCode', pattern: 'Array Traversal', estimatedTime: 30, link: 'https://leetcode.com/problems/product-of-array-except-self/', worldId: 2, patternId: 'w2-traversal' },
        ],
      },
      {
        id: 'w2-prefix',
        name: 'Prefix Sum',
        description: 'Precomputation technique for fast range query answers.',
        worldId: 2,
        problems: [
          { id: 'p2-4', title: 'Range Sum Query', difficulty: 'easy', platform: 'LeetCode', pattern: 'Prefix Sum', estimatedTime: 15, link: 'https://leetcode.com/problems/range-sum-query-immutable/', worldId: 2, patternId: 'w2-prefix' },
          { id: 'p2-5', title: 'Subarray Sum Equals K', difficulty: 'medium', platform: 'LeetCode', pattern: 'Prefix Sum', estimatedTime: 30, link: 'https://leetcode.com/problems/subarray-sum-equals-k/', worldId: 2, patternId: 'w2-prefix' },
          { id: 'p2-6', title: 'Count of Range Sum', difficulty: 'hard', platform: 'LeetCode', pattern: 'Prefix Sum', estimatedTime: 45, link: 'https://leetcode.com/problems/count-of-range-sum/', worldId: 2, patternId: 'w2-prefix' },
        ],
      },
      {
        id: 'w2-kadane',
        name: "Kadane's Algorithm",
        description: 'The classic maximum subarray sum algorithm.',
        worldId: 2,
        problems: [
          { id: 'p2-7', title: 'Maximum Subarray', difficulty: 'medium', platform: 'LeetCode', pattern: "Kadane's Algorithm", estimatedTime: 25, link: 'https://leetcode.com/problems/maximum-subarray/', worldId: 2, patternId: 'w2-kadane' },
          { id: 'p2-8', title: 'Maximum Sum Circular Subarray', difficulty: 'medium', platform: 'LeetCode', pattern: "Kadane's Algorithm", estimatedTime: 35, link: 'https://leetcode.com/problems/maximum-sum-circular-subarray/', worldId: 2, patternId: 'w2-kadane' },
          { id: 'p2-9', title: 'Maximum Product Subarray', difficulty: 'medium', platform: 'LeetCode', pattern: "Kadane's Algorithm", estimatedTime: 30, link: 'https://leetcode.com/problems/maximum-product-subarray/', worldId: 2, patternId: 'w2-kadane' },
        ],
      },
      {
        id: 'w2-hashing',
        name: 'Hashing Basics',
        description: 'Using hash maps and sets to optimize array problems.',
        worldId: 2,
        problems: [
          { id: 'p2-10', title: 'Two Sum', difficulty: 'easy', platform: 'LeetCode', pattern: 'Hashing Basics', estimatedTime: 15, link: 'https://leetcode.com/problems/two-sum/', worldId: 2, patternId: 'w2-hashing' },
          { id: 'p2-11', title: 'Longest Consecutive Sequence', difficulty: 'medium', platform: 'LeetCode', pattern: 'Hashing Basics', estimatedTime: 35, link: 'https://leetcode.com/problems/longest-consecutive-sequence/', worldId: 2, patternId: 'w2-hashing' },
          { id: 'p2-12', title: '4Sum II', difficulty: 'medium', platform: 'LeetCode', pattern: 'Hashing Basics', estimatedTime: 40, link: 'https://leetcode.com/problems/4sum-ii/', worldId: 2, patternId: 'w2-hashing' },
        ],
      },
    ],
  },
  {
    id: 3,
    name: 'HashMap Harbor',
    subtitle: 'Port of infinite lookups',
    description: 'Navigate the bustling harbor where every merchant trades in O(1) lookups. Master the art of hashing.',
    icon: '⚓',
    color: '#06b6d4',
    bgGradient: 'from-cyan-900/40 to-teal-800/20',
    boss: 'Memory Keeper',
    bossDescription: 'A spectral archivist who guards infinite scrolls of data. Defeat it by mastering O(1) lookup patterns.',
    position: { x: 42, y: 55 },
    patterns: [
      {
        id: 'w3-frequency',
        name: 'Frequency Maps',
        description: 'Count element occurrences and find patterns in frequency data.',
        worldId: 3,
        problems: [
          { id: 'p3-1', title: 'Valid Anagram', difficulty: 'easy', platform: 'LeetCode', pattern: 'Frequency Maps', estimatedTime: 15, link: 'https://leetcode.com/problems/valid-anagram/', worldId: 3, patternId: 'w3-frequency' },
          { id: 'p3-2', title: 'Top K Frequent Elements', difficulty: 'medium', platform: 'LeetCode', pattern: 'Frequency Maps', estimatedTime: 30, link: 'https://leetcode.com/problems/top-k-frequent-elements/', worldId: 3, patternId: 'w3-frequency' },
          { id: 'p3-3', title: 'Sort Characters By Frequency', difficulty: 'medium', platform: 'LeetCode', pattern: 'Frequency Maps', estimatedTime: 25, link: 'https://leetcode.com/problems/sort-characters-by-frequency/', worldId: 3, patternId: 'w3-frequency' },
        ],
      },
      {
        id: 'w3-pair',
        name: 'Pair Problems',
        description: 'Find pairs with specific properties using hash maps.',
        worldId: 3,
        problems: [
          { id: 'p3-4', title: 'Two Sum', difficulty: 'easy', platform: 'LeetCode', pattern: 'Pair Problems', estimatedTime: 15, link: 'https://leetcode.com/problems/two-sum/', worldId: 3, patternId: 'w3-pair' },
          { id: 'p3-5', title: 'Four Sum Count', difficulty: 'medium', platform: 'LeetCode', pattern: 'Pair Problems', estimatedTime: 35, link: 'https://leetcode.com/problems/4sum-ii/', worldId: 3, patternId: 'w3-pair' },
          { id: 'p3-6', title: 'Max Points on a Line', difficulty: 'hard', platform: 'LeetCode', pattern: 'Pair Problems', estimatedTime: 50, link: 'https://leetcode.com/problems/max-points-on-a-line/', worldId: 3, patternId: 'w3-pair' },
        ],
      },
      {
        id: 'w3-duplicate',
        name: 'Duplicate Detection',
        description: 'Efficiently detect duplicates and find unique elements.',
        worldId: 3,
        problems: [
          { id: 'p3-7', title: 'Contains Duplicate', difficulty: 'easy', platform: 'LeetCode', pattern: 'Duplicate Detection', estimatedTime: 10, link: 'https://leetcode.com/problems/contains-duplicate/', worldId: 3, patternId: 'w3-duplicate' },
          { id: 'p3-8', title: 'Find the Duplicate Number', difficulty: 'medium', platform: 'LeetCode', pattern: 'Duplicate Detection', estimatedTime: 30, link: 'https://leetcode.com/problems/find-the-duplicate-number/', worldId: 3, patternId: 'w3-duplicate' },
          { id: 'p3-9', title: 'First Missing Positive', difficulty: 'hard', platform: 'LeetCode', pattern: 'Duplicate Detection', estimatedTime: 45, link: 'https://leetcode.com/problems/first-missing-positive/', worldId: 3, patternId: 'w3-duplicate' },
        ],
      },
    ],
  },
  {
    id: 4,
    name: 'Two Pointer Valley',
    subtitle: 'Dance of the twin blades',
    description: 'Master the elegant dance of two pointers moving through arrays like twin blades, reducing O(n²) to O(n).',
    icon: '⚔️',
    color: '#8b5cf6',
    bgGradient: 'from-violet-900/40 to-purple-800/20',
    boss: 'Twin Dragons',
    bossDescription: 'Two massive serpents that move in perfect sync. Only by mastering opposite and same-direction pointer techniques can you defeat them.',
    position: { x: 55, y: 48 },
    patterns: [
      {
        id: 'w4-opposite',
        name: 'Opposite Direction',
        description: 'Two pointers from both ends converging to the center.',
        worldId: 4,
        problems: [
          { id: 'p4-1', title: 'Valid Palindrome', difficulty: 'easy', platform: 'LeetCode', pattern: 'Opposite Direction', estimatedTime: 15, link: 'https://leetcode.com/problems/valid-palindrome/', worldId: 4, patternId: 'w4-opposite' },
          { id: 'p4-2', title: 'Two Sum II', difficulty: 'medium', platform: 'LeetCode', pattern: 'Opposite Direction', estimatedTime: 20, link: 'https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/', worldId: 4, patternId: 'w4-opposite' },
          { id: 'p4-3', title: 'Container With Most Water', difficulty: 'medium', platform: 'LeetCode', pattern: 'Opposite Direction', estimatedTime: 30, link: 'https://leetcode.com/problems/container-with-most-water/', worldId: 4, patternId: 'w4-opposite' },
          { id: 'p4-4', title: 'Trapping Rain Water', difficulty: 'hard', platform: 'LeetCode', pattern: 'Opposite Direction', estimatedTime: 45, link: 'https://leetcode.com/problems/trapping-rain-water/', worldId: 4, patternId: 'w4-opposite' },
        ],
      },
      {
        id: 'w4-fastslow',
        name: 'Fast & Slow Pointer',
        description: 'Using pointers at different speeds to detect cycles and find midpoints.',
        worldId: 4,
        problems: [
          { id: 'p4-5', title: 'Linked List Cycle', difficulty: 'easy', platform: 'LeetCode', pattern: 'Fast & Slow Pointer', estimatedTime: 15, link: 'https://leetcode.com/problems/linked-list-cycle/', worldId: 4, patternId: 'w4-fastslow' },
          { id: 'p4-6', title: 'Middle of the Linked List', difficulty: 'easy', platform: 'LeetCode', pattern: 'Fast & Slow Pointer', estimatedTime: 15, link: 'https://leetcode.com/problems/middle-of-the-linked-list/', worldId: 4, patternId: 'w4-fastslow' },
          { id: 'p4-7', title: 'Find the Duplicate Number', difficulty: 'medium', platform: 'LeetCode', pattern: 'Fast & Slow Pointer', estimatedTime: 30, link: 'https://leetcode.com/problems/find-the-duplicate-number/', worldId: 4, patternId: 'w4-fastslow' },
        ],
      },
    ],
  },
  {
    id: 5,
    name: 'Sliding Window Ocean',
    subtitle: 'Waves of optimal subarrays',
    description: 'Ride the waves of the Sliding Window Ocean, harnessing the power of dynamic windows to solve subarray and substring problems.',
    icon: '🌊',
    color: '#0ea5e9',
    bgGradient: 'from-sky-900/40 to-blue-800/20',
    boss: 'Kraken of Subarrays',
    bossDescription: 'A massive sea beast whose tentacles represent overlapping windows. Master variable and fixed windows to slay it.',
    position: { x: 68, y: 42 },
    patterns: [
      {
        id: 'w5-fixed',
        name: 'Fixed Window',
        description: 'Maintaining a window of constant size through an array.',
        worldId: 5,
        problems: [
          { id: 'p5-1', title: 'Maximum Average Subarray I', difficulty: 'easy', platform: 'LeetCode', pattern: 'Fixed Window', estimatedTime: 15, link: 'https://leetcode.com/problems/maximum-average-subarray-i/', worldId: 5, patternId: 'w5-fixed' },
          { id: 'p5-2', title: 'Substrings of Size Three with Distinct Characters', difficulty: 'easy', platform: 'LeetCode', pattern: 'Fixed Window', estimatedTime: 20, link: 'https://leetcode.com/problems/substrings-of-size-three-with-distinct-characters/', worldId: 5, patternId: 'w5-fixed' },
        ],
      },
      {
        id: 'w5-variable',
        name: 'Variable Window',
        description: 'Dynamically expanding and shrinking the window based on conditions.',
        worldId: 5,
        problems: [
          { id: 'p5-3', title: 'Longest Substring Without Repeating Characters', difficulty: 'medium', platform: 'LeetCode', pattern: 'Variable Window', estimatedTime: 25, link: 'https://leetcode.com/problems/longest-substring-without-repeating-characters/', worldId: 5, patternId: 'w5-variable' },
          { id: 'p5-4', title: 'Minimum Window Substring', difficulty: 'hard', platform: 'LeetCode', pattern: 'Variable Window', estimatedTime: 50, link: 'https://leetcode.com/problems/minimum-window-substring/', worldId: 5, patternId: 'w5-variable' },
          { id: 'p5-5', title: 'Longest Repeating Character Replacement', difficulty: 'medium', platform: 'LeetCode', pattern: 'Variable Window', estimatedTime: 35, link: 'https://leetcode.com/problems/longest-repeating-character-replacement/', worldId: 5, patternId: 'w5-variable' },
        ],
      },
    ],
  },
  {
    id: 6,
    name: 'Sorting Kingdom',
    subtitle: 'Order from chaos',
    description: 'The kingdom where chaos becomes order. Master all sorting algorithms from comparison-based to counting sorts.',
    icon: '👑',
    color: '#ec4899',
    bgGradient: 'from-pink-900/40 to-rose-800/20',
    boss: 'Order Lord',
    bossDescription: 'An armored giant who rules through perfect order. Defeat it by demonstrating mastery of every sorting algorithm.',
    position: { x: 78, y: 35 },
    patterns: [
      {
        id: 'w6-comparison',
        name: 'Comparison Sorts',
        description: 'Bubble, Selection, Insertion — the classical sorting family.',
        worldId: 6,
        problems: [
          { id: 'p6-1', title: 'Sort an Array', difficulty: 'medium', platform: 'LeetCode', pattern: 'Comparison Sorts', estimatedTime: 25, link: 'https://leetcode.com/problems/sort-an-array/', worldId: 6, patternId: 'w6-comparison' },
          { id: 'p6-2', title: 'Insertion Sort List', difficulty: 'medium', platform: 'LeetCode', pattern: 'Comparison Sorts', estimatedTime: 30, link: 'https://leetcode.com/problems/insertion-sort-list/', worldId: 6, patternId: 'w6-comparison' },
        ],
      },
      {
        id: 'w6-advanced',
        name: 'Advanced Sorts',
        description: 'Merge Sort, Quick Sort, Heap Sort — divide and conquer sorting.',
        worldId: 6,
        problems: [
          { id: 'p6-3', title: 'Sort List', difficulty: 'medium', platform: 'LeetCode', pattern: 'Advanced Sorts', estimatedTime: 35, link: 'https://leetcode.com/problems/sort-list/', worldId: 6, patternId: 'w6-advanced' },
          { id: 'p6-4', title: 'Kth Largest Element in Array', difficulty: 'medium', platform: 'LeetCode', pattern: 'Advanced Sorts', estimatedTime: 30, link: 'https://leetcode.com/problems/kth-largest-element-in-an-array/', worldId: 6, patternId: 'w6-advanced' },
          { id: 'p6-5', title: 'Count of Smaller Numbers After Self', difficulty: 'hard', platform: 'LeetCode', pattern: 'Advanced Sorts', estimatedTime: 55, link: 'https://leetcode.com/problems/count-of-smaller-numbers-after-self/', worldId: 6, patternId: 'w6-advanced' },
        ],
      },
    ],
  },
  {
    id: 7,
    name: 'Binary Search Mountains',
    subtitle: 'Summit of logarithmic power',
    description: 'Scale the Binary Search Mountains and harness the power of logarithmic search on sorted data and monotonic answer spaces.',
    icon: '⛰️',
    color: '#64748b',
    bgGradient: 'from-slate-900/40 to-gray-800/20',
    boss: 'Mountain Sentinel',
    bossDescription: 'A stone golem perched at the peak who can only be defeated by finding the exact answer in log(n) time.',
    position: { x: 85, y: 28 },
    patterns: [
      {
        id: 'w7-classic',
        name: 'Classic Binary Search',
        description: 'The foundational binary search on sorted arrays.',
        worldId: 7,
        problems: [
          { id: 'p7-1', title: 'Binary Search', difficulty: 'easy', platform: 'LeetCode', pattern: 'Classic Binary Search', estimatedTime: 15, link: 'https://leetcode.com/problems/binary-search/', worldId: 7, patternId: 'w7-classic' },
          { id: 'p7-2', title: 'Search in Rotated Sorted Array', difficulty: 'medium', platform: 'LeetCode', pattern: 'Classic Binary Search', estimatedTime: 30, link: 'https://leetcode.com/problems/search-in-rotated-sorted-array/', worldId: 7, patternId: 'w7-classic' },
          { id: 'p7-3', title: 'Find Minimum in Rotated Sorted Array', difficulty: 'medium', platform: 'LeetCode', pattern: 'Classic Binary Search', estimatedTime: 25, link: 'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/', worldId: 7, patternId: 'w7-classic' },
        ],
      },
      {
        id: 'w7-answer',
        name: 'Search on Answer',
        description: 'Binary searching on the answer space rather than an array.',
        worldId: 7,
        problems: [
          { id: 'p7-4', title: 'Koko Eating Bananas', difficulty: 'medium', platform: 'LeetCode', pattern: 'Search on Answer', estimatedTime: 30, link: 'https://leetcode.com/problems/koko-eating-bananas/', worldId: 7, patternId: 'w7-answer' },
          { id: 'p7-5', title: 'Capacity To Ship Packages', difficulty: 'medium', platform: 'LeetCode', pattern: 'Search on Answer', estimatedTime: 35, link: 'https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/', worldId: 7, patternId: 'w7-answer' },
          { id: 'p7-6', title: 'Split Array Largest Sum', difficulty: 'hard', platform: 'LeetCode', pattern: 'Search on Answer', estimatedTime: 50, link: 'https://leetcode.com/problems/split-array-largest-sum/', worldId: 7, patternId: 'w7-answer' },
        ],
      },
    ],
  },
  {
    id: 8,
    name: 'Recursion Volcano',
    subtitle: 'Eruptions of self-reference',
    description: 'Dive into the fiery depths of recursive thinking. Master the art of breaking down problems into their smallest subproblems.',
    icon: '🌋',
    color: '#ef4444',
    bgGradient: 'from-red-900/40 to-orange-800/20',
    boss: 'Infinite Phoenix',
    bossDescription: 'A creature that resurrects infinitely — mirroring recursion itself. Defeat it by mastering base cases and divide-and-conquer.',
    position: { x: 72, y: 22 },
    patterns: [
      {
        id: 'w8-basic',
        name: 'Basic Recursion',
        description: 'Foundation of recursive thinking — base cases and recursive leaps.',
        worldId: 8,
        problems: [
          { id: 'p8-1', title: 'Power of Two', difficulty: 'easy', platform: 'LeetCode', pattern: 'Basic Recursion', estimatedTime: 15, link: 'https://leetcode.com/problems/power-of-two/', worldId: 8, patternId: 'w8-basic' },
          { id: 'p8-2', title: 'Reverse String', difficulty: 'easy', platform: 'LeetCode', pattern: 'Basic Recursion', estimatedTime: 15, link: 'https://leetcode.com/problems/reverse-string/', worldId: 8, patternId: 'w8-basic' },
          { id: 'p8-3', title: 'Merge Sort Array', difficulty: 'medium', platform: 'LeetCode', pattern: 'Basic Recursion', estimatedTime: 30, link: 'https://leetcode.com/problems/sort-an-array/', worldId: 8, patternId: 'w8-basic' },
        ],
      },
      {
        id: 'w8-divconquer',
        name: 'Divide & Conquer',
        description: 'Splitting problems recursively and combining results.',
        worldId: 8,
        problems: [
          { id: 'p8-4', title: 'Maximum Depth of Binary Tree', difficulty: 'easy', platform: 'LeetCode', pattern: 'Divide & Conquer', estimatedTime: 15, link: 'https://leetcode.com/problems/maximum-depth-of-binary-tree/', worldId: 8, patternId: 'w8-divconquer' },
          { id: 'p8-5', title: 'Search a 2D Matrix II', difficulty: 'medium', platform: 'LeetCode', pattern: 'Divide & Conquer', estimatedTime: 30, link: 'https://leetcode.com/problems/search-a-2d-matrix-ii/', worldId: 8, patternId: 'w8-divconquer' },
          { id: 'p8-6', title: 'Largest Rectangle in Histogram', difficulty: 'hard', platform: 'LeetCode', pattern: 'Divide & Conquer', estimatedTime: 50, link: 'https://leetcode.com/problems/largest-rectangle-in-histogram/', worldId: 8, patternId: 'w8-divconquer' },
        ],
      },
    ],
  },
  {
    id: 9,
    name: 'Backtracking Caverns',
    subtitle: 'Labyrinth of choices',
    description: 'Explore the dark caverns of decision trees. Learn to explore all possibilities and backtrack from dead ends.',
    icon: '🕌',
    color: '#a855f7',
    bgGradient: 'from-purple-900/40 to-violet-800/20',
    boss: 'Shadow Architect',
    bossDescription: 'A phantom architect who builds infinite mazes. Defeat it by mastering decision trees and pruning techniques.',
    position: { x: 58, y: 18 },
    patterns: [
      {
        id: 'w9-subsets',
        name: 'Subsets & Combinations',
        description: 'Generating all possible subsets and combinations.',
        worldId: 9,
        problems: [
          { id: 'p9-1', title: 'Subsets', difficulty: 'medium', platform: 'LeetCode', pattern: 'Subsets & Combinations', estimatedTime: 25, link: 'https://leetcode.com/problems/subsets/', worldId: 9, patternId: 'w9-subsets' },
          { id: 'p9-2', title: 'Combination Sum', difficulty: 'medium', platform: 'LeetCode', pattern: 'Subsets & Combinations', estimatedTime: 30, link: 'https://leetcode.com/problems/combination-sum/', worldId: 9, patternId: 'w9-subsets' },
          { id: 'p9-3', title: 'Subsets II', difficulty: 'medium', platform: 'LeetCode', pattern: 'Subsets & Combinations', estimatedTime: 30, link: 'https://leetcode.com/problems/subsets-ii/', worldId: 9, patternId: 'w9-subsets' },
        ],
      },
      {
        id: 'w9-permutations',
        name: 'Permutations',
        description: 'Generating all possible orderings of elements.',
        worldId: 9,
        problems: [
          { id: 'p9-4', title: 'Permutations', difficulty: 'medium', platform: 'LeetCode', pattern: 'Permutations', estimatedTime: 25, link: 'https://leetcode.com/problems/permutations/', worldId: 9, patternId: 'w9-permutations' },
          { id: 'p9-5', title: 'Permutations II', difficulty: 'medium', platform: 'LeetCode', pattern: 'Permutations', estimatedTime: 30, link: 'https://leetcode.com/problems/permutations-ii/', worldId: 9, patternId: 'w9-permutations' },
          { id: 'p9-6', title: 'N-Queens', difficulty: 'hard', platform: 'LeetCode', pattern: 'Permutations', estimatedTime: 60, link: 'https://leetcode.com/problems/n-queens/', worldId: 9, patternId: 'w9-permutations' },
        ],
      },
    ],
  },
  {
    id: 10,
    name: 'Linked List Marshlands',
    subtitle: 'Chains through the swamp',
    description: 'Traverse the murky marshlands of linked data. Master pointer manipulation across these chained nodes.',
    icon: '🔗',
    color: '#14b8a6',
    bgGradient: 'from-teal-900/40 to-green-800/20',
    boss: 'Swamp Hydra',
    bossDescription: 'A multi-headed hydra — each head a linked list. Defeat it by mastering cycle detection, reversal, and merging.',
    position: { x: 45, y: 15 },
    patterns: [
      {
        id: 'w10-reversal',
        name: 'Reversal Patterns',
        description: 'Reversing linked lists in full, partially, or in groups.',
        worldId: 10,
        problems: [
          { id: 'p10-1', title: 'Reverse Linked List', difficulty: 'easy', platform: 'LeetCode', pattern: 'Reversal Patterns', estimatedTime: 15, link: 'https://leetcode.com/problems/reverse-linked-list/', worldId: 10, patternId: 'w10-reversal' },
          { id: 'p10-2', title: 'Reverse Linked List II', difficulty: 'medium', platform: 'LeetCode', pattern: 'Reversal Patterns', estimatedTime: 30, link: 'https://leetcode.com/problems/reverse-linked-list-ii/', worldId: 10, patternId: 'w10-reversal' },
          { id: 'p10-3', title: 'Reverse Nodes in k-Group', difficulty: 'hard', platform: 'LeetCode', pattern: 'Reversal Patterns', estimatedTime: 50, link: 'https://leetcode.com/problems/reverse-nodes-in-k-group/', worldId: 10, patternId: 'w10-reversal' },
        ],
      },
      {
        id: 'w10-cycle',
        name: 'Cycle Detection',
        description: 'Detecting and finding cycles in linked lists using Floyd\'s algorithm.',
        worldId: 10,
        problems: [
          { id: 'p10-4', title: 'Linked List Cycle', difficulty: 'easy', platform: 'LeetCode', pattern: 'Cycle Detection', estimatedTime: 15, link: 'https://leetcode.com/problems/linked-list-cycle/', worldId: 10, patternId: 'w10-cycle' },
          { id: 'p10-5', title: 'Linked List Cycle II', difficulty: 'medium', platform: 'LeetCode', pattern: 'Cycle Detection', estimatedTime: 30, link: 'https://leetcode.com/problems/linked-list-cycle-ii/', worldId: 10, patternId: 'w10-cycle' },
        ],
      },
    ],
  },
  {
    id: 11,
    name: 'Stack Fortress',
    subtitle: 'Iron walls of LIFO',
    description: 'Breach the walls of Stack Fortress. Master monotonic stacks and expression evaluation within its iron halls.',
    icon: '🏰',
    color: '#f97316',
    bgGradient: 'from-orange-900/40 to-red-800/20',
    boss: 'Iron Titan',
    bossDescription: 'A towering iron colossus that relies on brute force. Defeat it elegantly using monotonic stack patterns.',
    position: { x: 32, y: 12 },
    patterns: [
      {
        id: 'w11-monotonic',
        name: 'Monotonic Stack',
        description: 'Maintaining a stack with monotonic ordering properties.',
        worldId: 11,
        problems: [
          { id: 'p11-1', title: 'Daily Temperatures', difficulty: 'medium', platform: 'LeetCode', pattern: 'Monotonic Stack', estimatedTime: 25, link: 'https://leetcode.com/problems/daily-temperatures/', worldId: 11, patternId: 'w11-monotonic' },
          { id: 'p11-2', title: 'Next Greater Element I', difficulty: 'easy', platform: 'LeetCode', pattern: 'Monotonic Stack', estimatedTime: 20, link: 'https://leetcode.com/problems/next-greater-element-i/', worldId: 11, patternId: 'w11-monotonic' },
          { id: 'p11-3', title: 'Largest Rectangle in Histogram', difficulty: 'hard', platform: 'LeetCode', pattern: 'Monotonic Stack', estimatedTime: 55, link: 'https://leetcode.com/problems/largest-rectangle-in-histogram/', worldId: 11, patternId: 'w11-monotonic' },
        ],
      },
      {
        id: 'w11-parentheses',
        name: 'Parentheses Problems',
        description: 'Using stacks to validate and generate parenthesis expressions.',
        worldId: 11,
        problems: [
          { id: 'p11-4', title: 'Valid Parentheses', difficulty: 'easy', platform: 'LeetCode', pattern: 'Parentheses Problems', estimatedTime: 15, link: 'https://leetcode.com/problems/valid-parentheses/', worldId: 11, patternId: 'w11-parentheses' },
          { id: 'p11-5', title: 'Generate Parentheses', difficulty: 'medium', platform: 'LeetCode', pattern: 'Parentheses Problems', estimatedTime: 30, link: 'https://leetcode.com/problems/generate-parentheses/', worldId: 11, patternId: 'w11-parentheses' },
          { id: 'p11-6', title: 'Longest Valid Parentheses', difficulty: 'hard', platform: 'LeetCode', pattern: 'Parentheses Problems', estimatedTime: 50, link: 'https://leetcode.com/problems/longest-valid-parentheses/', worldId: 11, patternId: 'w11-parentheses' },
        ],
      },
    ],
  },
  {
    id: 12,
    name: 'Queue Citadel',
    subtitle: 'Fortress of ordered time',
    description: 'The Queue Citadel operates on strict order. Master FIFO principles, deques, and monotonic queues.',
    icon: '🕐',
    color: '#6366f1',
    bgGradient: 'from-indigo-900/40 to-blue-800/20',
    boss: 'Time Warden',
    bossDescription: 'A temporal guardian who controls the flow of time (and data). Master queue patterns to override its power.',
    position: { x: 20, y: 10 },
    patterns: [
      {
        id: 'w12-bfs',
        name: 'BFS with Queues',
        description: 'Breadth-first search patterns using queues.',
        worldId: 12,
        problems: [
          { id: 'p12-1', title: 'Binary Tree Level Order Traversal', difficulty: 'medium', platform: 'LeetCode', pattern: 'BFS with Queues', estimatedTime: 25, link: 'https://leetcode.com/problems/binary-tree-level-order-traversal/', worldId: 12, patternId: 'w12-bfs' },
          { id: 'p12-2', title: 'Number of Islands', difficulty: 'medium', platform: 'LeetCode', pattern: 'BFS with Queues', estimatedTime: 30, link: 'https://leetcode.com/problems/number-of-islands/', worldId: 12, patternId: 'w12-bfs' },
          { id: 'p12-3', title: 'Shortest Path in Binary Matrix', difficulty: 'medium', platform: 'LeetCode', pattern: 'BFS with Queues', estimatedTime: 35, link: 'https://leetcode.com/problems/shortest-path-in-binary-matrix/', worldId: 12, patternId: 'w12-bfs' },
        ],
      },
      {
        id: 'w12-deque',
        name: 'Deque & Monotonic Queue',
        description: 'Double-ended queues for efficient sliding window problems.',
        worldId: 12,
        problems: [
          { id: 'p12-4', title: 'Sliding Window Maximum', difficulty: 'hard', platform: 'LeetCode', pattern: 'Deque & Monotonic Queue', estimatedTime: 45, link: 'https://leetcode.com/problems/sliding-window-maximum/', worldId: 12, patternId: 'w12-deque' },
          { id: 'p12-5', title: 'Design Circular Deque', difficulty: 'medium', platform: 'LeetCode', pattern: 'Deque & Monotonic Queue', estimatedTime: 35, link: 'https://leetcode.com/problems/design-circular-deque/', worldId: 12, patternId: 'w12-deque' },
        ],
      },
    ],
  },
  {
    id: 13,
    name: 'Heap Highlands',
    subtitle: 'Heights of priority',
    description: 'Ascend the Heap Highlands where priority reigns supreme. Master heap operations and Top-K patterns.',
    icon: '⛏️',
    color: '#84cc16',
    bgGradient: 'from-lime-900/40 to-green-800/20',
    boss: 'Heap Giant',
    bossDescription: 'A giant forged from layers of priority. Defeat it using heap operations in O(log n) time.',
    position: { x: 10, y: 30 },
    patterns: [
      {
        id: 'w13-topk',
        name: 'Top K Problems',
        description: 'Finding the k largest, smallest, or most frequent elements.',
        worldId: 13,
        problems: [
          { id: 'p13-1', title: 'Kth Largest Element in a Stream', difficulty: 'easy', platform: 'LeetCode', pattern: 'Top K Problems', estimatedTime: 20, link: 'https://leetcode.com/problems/kth-largest-element-in-a-stream/', worldId: 13, patternId: 'w13-topk' },
          { id: 'p13-2', title: 'Top K Frequent Elements', difficulty: 'medium', platform: 'LeetCode', pattern: 'Top K Problems', estimatedTime: 30, link: 'https://leetcode.com/problems/top-k-frequent-elements/', worldId: 13, patternId: 'w13-topk' },
          { id: 'p13-3', title: 'Find Median from Data Stream', difficulty: 'hard', platform: 'LeetCode', pattern: 'Top K Problems', estimatedTime: 55, link: 'https://leetcode.com/problems/find-median-from-data-stream/', worldId: 13, patternId: 'w13-topk' },
        ],
      },
    ],
  },
  {
    id: 14,
    name: 'Greedy Kingdom',
    subtitle: 'Realm of optimal choices',
    description: 'In the Greedy Kingdom, every local optimal choice leads to global victory. Master the greedy strategy.',
    icon: '💰',
    color: '#eab308',
    bgGradient: 'from-yellow-900/40 to-amber-800/20',
    boss: 'Golden Strategist',
    bossDescription: 'A master tactician who defeats opponents with perfectly optimal choices. Prove you can make greedy decisions.',
    position: { x: 12, y: 48 },
    patterns: [
      {
        id: 'w14-intervals',
        name: 'Interval Scheduling',
        description: 'Greedy approaches to scheduling and interval problems.',
        worldId: 14,
        problems: [
          { id: 'p14-1', title: 'Non-overlapping Intervals', difficulty: 'medium', platform: 'LeetCode', pattern: 'Interval Scheduling', estimatedTime: 25, link: 'https://leetcode.com/problems/non-overlapping-intervals/', worldId: 14, patternId: 'w14-intervals' },
          { id: 'p14-2', title: 'Merge Intervals', difficulty: 'medium', platform: 'LeetCode', pattern: 'Interval Scheduling', estimatedTime: 30, link: 'https://leetcode.com/problems/merge-intervals/', worldId: 14, patternId: 'w14-intervals' },
          { id: 'p14-3', title: 'Minimum Number of Arrows', difficulty: 'medium', platform: 'LeetCode', pattern: 'Interval Scheduling', estimatedTime: 30, link: 'https://leetcode.com/problems/minimum-number-of-arrows-to-burst-balloons/', worldId: 14, patternId: 'w14-intervals' },
        ],
      },
      {
        id: 'w14-greedy',
        name: 'Greedy Choice Property',
        description: 'Making locally optimal choices that guarantee a global optimum.',
        worldId: 14,
        problems: [
          { id: 'p14-4', title: 'Jump Game', difficulty: 'medium', platform: 'LeetCode', pattern: 'Greedy Choice Property', estimatedTime: 25, link: 'https://leetcode.com/problems/jump-game/', worldId: 14, patternId: 'w14-greedy' },
          { id: 'p14-5', title: 'Gas Station', difficulty: 'medium', platform: 'LeetCode', pattern: 'Greedy Choice Property', estimatedTime: 30, link: 'https://leetcode.com/problems/gas-station/', worldId: 14, patternId: 'w14-greedy' },
          { id: 'p14-6', title: "Candy", difficulty: 'hard', platform: 'LeetCode', pattern: 'Greedy Choice Property', estimatedTime: 45, link: 'https://leetcode.com/problems/candy/', worldId: 14, patternId: 'w14-greedy' },
        ],
      },
    ],
  },
  {
    id: 15,
    name: 'Tree Kingdom',
    subtitle: 'Ancient arboreal empire',
    description: 'The ancient Tree Kingdom stretches infinitely upward. Master every tree traversal and manipulation technique.',
    icon: '🌳',
    color: '#22c55e',
    bgGradient: 'from-green-900/40 to-teal-800/20',
    boss: 'Ancient Tree Lord',
    bossDescription: 'A primordial tree spirit whose roots span the entire kingdom. Defeat it through mastery of DFS, BFS, and tree construction.',
    position: { x: 25, y: 38 },
    patterns: [
      {
        id: 'w15-traversals',
        name: 'Tree Traversals',
        description: 'Inorder, Preorder, Postorder, Level Order — all tree traversal methods.',
        worldId: 15,
        problems: [
          { id: 'p15-1', title: 'Binary Tree Inorder Traversal', difficulty: 'easy', platform: 'LeetCode', pattern: 'Tree Traversals', estimatedTime: 15, link: 'https://leetcode.com/problems/binary-tree-inorder-traversal/', worldId: 15, patternId: 'w15-traversals' },
          { id: 'p15-2', title: 'Binary Tree Level Order Traversal', difficulty: 'medium', platform: 'LeetCode', pattern: 'Tree Traversals', estimatedTime: 25, link: 'https://leetcode.com/problems/binary-tree-level-order-traversal/', worldId: 15, patternId: 'w15-traversals' },
          { id: 'p15-3', title: 'Serialize and Deserialize Binary Tree', difficulty: 'hard', platform: 'LeetCode', pattern: 'Tree Traversals', estimatedTime: 55, link: 'https://leetcode.com/problems/serialize-and-deserialize-binary-tree/', worldId: 15, patternId: 'w15-traversals' },
        ],
      },
      {
        id: 'w15-bst',
        name: 'Binary Search Trees',
        description: 'BST properties, insertion, deletion, and validation.',
        worldId: 15,
        problems: [
          { id: 'p15-4', title: 'Validate Binary Search Tree', difficulty: 'medium', platform: 'LeetCode', pattern: 'Binary Search Trees', estimatedTime: 25, link: 'https://leetcode.com/problems/validate-binary-search-tree/', worldId: 15, patternId: 'w15-bst' },
          { id: 'p15-5', title: 'Kth Smallest Element in BST', difficulty: 'medium', platform: 'LeetCode', pattern: 'Binary Search Trees', estimatedTime: 20, link: 'https://leetcode.com/problems/kth-smallest-element-in-a-bst/', worldId: 15, patternId: 'w15-bst' },
          { id: 'p15-6', title: 'Lowest Common Ancestor BST', difficulty: 'medium', platform: 'LeetCode', pattern: 'Binary Search Trees', estimatedTime: 20, link: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/', worldId: 15, patternId: 'w15-bst' },
        ],
      },
    ],
  },
  {
    id: 16,
    name: 'Graph Empire',
    subtitle: 'Interconnected dominion',
    description: 'The vast Graph Empire spans across infinite nodes and edges. Master every graph algorithm from DFS to Dijkstra.',
    icon: '🗺️',
    color: '#3b82f6',
    bgGradient: 'from-blue-900/40 to-cyan-800/20',
    boss: 'Graph Emperor',
    bossDescription: 'The supreme ruler of interconnected systems. Only a master of DFS, BFS, Dijkstra, and Union-Find can overthrow it.',
    position: { x: 38, y: 30 },
    patterns: [
      {
        id: 'w16-dfs-bfs',
        name: 'Graph DFS & BFS',
        description: 'Core graph traversal algorithms for exploring nodes and edges.',
        worldId: 16,
        problems: [
          { id: 'p16-1', title: 'Number of Islands', difficulty: 'medium', platform: 'LeetCode', pattern: 'Graph DFS & BFS', estimatedTime: 25, link: 'https://leetcode.com/problems/number-of-islands/', worldId: 16, patternId: 'w16-dfs-bfs' },
          { id: 'p16-2', title: 'Clone Graph', difficulty: 'medium', platform: 'LeetCode', pattern: 'Graph DFS & BFS', estimatedTime: 30, link: 'https://leetcode.com/problems/clone-graph/', worldId: 16, patternId: 'w16-dfs-bfs' },
          { id: 'p16-3', title: 'Pacific Atlantic Water Flow', difficulty: 'medium', platform: 'LeetCode', pattern: 'Graph DFS & BFS', estimatedTime: 35, link: 'https://leetcode.com/problems/pacific-atlantic-water-flow/', worldId: 16, patternId: 'w16-dfs-bfs' },
        ],
      },
      {
        id: 'w16-shortest',
        name: 'Shortest Path Algorithms',
        description: 'Dijkstra, Bellman-Ford, Floyd-Warshall for weighted graphs.',
        worldId: 16,
        problems: [
          { id: 'p16-4', title: 'Network Delay Time', difficulty: 'medium', platform: 'LeetCode', pattern: 'Shortest Path Algorithms', estimatedTime: 35, link: 'https://leetcode.com/problems/network-delay-time/', worldId: 16, patternId: 'w16-shortest' },
          { id: 'p16-5', title: 'Cheapest Flights Within K Stops', difficulty: 'medium', platform: 'LeetCode', pattern: 'Shortest Path Algorithms', estimatedTime: 40, link: 'https://leetcode.com/problems/cheapest-flights-within-k-stops/', worldId: 16, patternId: 'w16-shortest' },
          { id: 'p16-6', title: 'Find the City With Smallest Reachable Neighbors', difficulty: 'medium', platform: 'LeetCode', pattern: 'Shortest Path Algorithms', estimatedTime: 35, link: 'https://leetcode.com/problems/find-the-city-with-the-smallest-number-of-neighbors-at-a-threshold-distance/', worldId: 16, patternId: 'w16-shortest' },
        ],
      },
      {
        id: 'w16-unionfind',
        name: 'Union Find',
        description: 'Disjoint set union for dynamic connectivity problems.',
        worldId: 16,
        problems: [
          { id: 'p16-7', title: 'Number of Connected Components', difficulty: 'medium', platform: 'LeetCode', pattern: 'Union Find', estimatedTime: 25, link: 'https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/', worldId: 16, patternId: 'w16-unionfind' },
          { id: 'p16-8', title: 'Redundant Connection', difficulty: 'medium', platform: 'LeetCode', pattern: 'Union Find', estimatedTime: 30, link: 'https://leetcode.com/problems/redundant-connection/', worldId: 16, patternId: 'w16-unionfind' },
          { id: 'p16-9', title: 'Accounts Merge', difficulty: 'medium', platform: 'LeetCode', pattern: 'Union Find', estimatedTime: 40, link: 'https://leetcode.com/problems/accounts-merge/', worldId: 16, patternId: 'w16-unionfind' },
        ],
      },
    ],
  },
  {
    id: 17,
    name: 'Trie Dimension',
    subtitle: 'Library of prefix wisdom',
    description: 'The Trie Dimension holds every word ever written. Master prefix trees for lightning-fast string operations.',
    icon: '📚',
    color: '#10b981',
    bgGradient: 'from-emerald-900/40 to-teal-800/20',
    boss: 'Word Weaver',
    bossDescription: 'An ancient librarian who controls all language. Defeat it by mastering prefix search and autocomplete patterns.',
    position: { x: 50, y: 28 },
    patterns: [
      {
        id: 'w17-trie',
        name: 'Trie Operations',
        description: 'Building and querying tries for prefix-based operations.',
        worldId: 17,
        problems: [
          { id: 'p17-1', title: 'Implement Trie', difficulty: 'medium', platform: 'LeetCode', pattern: 'Trie Operations', estimatedTime: 30, link: 'https://leetcode.com/problems/implement-trie-prefix-tree/', worldId: 17, patternId: 'w17-trie' },
          { id: 'p17-2', title: 'Word Search II', difficulty: 'hard', platform: 'LeetCode', pattern: 'Trie Operations', estimatedTime: 60, link: 'https://leetcode.com/problems/word-search-ii/', worldId: 17, patternId: 'w17-trie' },
          { id: 'p17-3', title: 'Design Add and Search Words', difficulty: 'medium', platform: 'LeetCode', pattern: 'Trie Operations', estimatedTime: 35, link: 'https://leetcode.com/problems/design-add-and-search-words-data-structure/', worldId: 17, patternId: 'w17-trie' },
        ],
      },
    ],
  },
  {
    id: 18,
    name: 'Bit Manipulation Laboratory',
    subtitle: 'The binary forge',
    description: 'Deep in the Binary Forge, ones and zeros dance. Master bit manipulation for problems that seem impossible otherwise.',
    icon: '⚡',
    color: '#f59e0b',
    bgGradient: 'from-amber-900/40 to-yellow-800/20',
    boss: 'Binary Alchemist',
    bossDescription: 'A sorcerer who transmutes data at the binary level. Defeat it by mastering XOR, bitmasking, and binary operations.',
    position: { x: 62, y: 35 },
    patterns: [
      {
        id: 'w18-xor',
        name: 'XOR Tricks',
        description: 'Exploiting XOR properties for elegant constant-space solutions.',
        worldId: 18,
        problems: [
          { id: 'p18-1', title: 'Single Number', difficulty: 'easy', platform: 'LeetCode', pattern: 'XOR Tricks', estimatedTime: 15, link: 'https://leetcode.com/problems/single-number/', worldId: 18, patternId: 'w18-xor' },
          { id: 'p18-2', title: 'Single Number II', difficulty: 'medium', platform: 'LeetCode', pattern: 'XOR Tricks', estimatedTime: 30, link: 'https://leetcode.com/problems/single-number-ii/', worldId: 18, patternId: 'w18-xor' },
          { id: 'p18-3', title: 'Missing Number', difficulty: 'easy', platform: 'LeetCode', pattern: 'XOR Tricks', estimatedTime: 15, link: 'https://leetcode.com/problems/missing-number/', worldId: 18, patternId: 'w18-xor' },
        ],
      },
      {
        id: 'w18-bitmask',
        name: 'Bitmasking',
        description: 'Using bitmasks to represent sets and states efficiently.',
        worldId: 18,
        problems: [
          { id: 'p18-4', title: 'Counting Bits', difficulty: 'easy', platform: 'LeetCode', pattern: 'Bitmasking', estimatedTime: 15, link: 'https://leetcode.com/problems/counting-bits/', worldId: 18, patternId: 'w18-bitmask' },
          { id: 'p18-5', title: 'Number of 1 Bits', difficulty: 'easy', platform: 'LeetCode', pattern: 'Bitmasking', estimatedTime: 10, link: 'https://leetcode.com/problems/number-of-1-bits/', worldId: 18, patternId: 'w18-bitmask' },
          { id: 'p18-6', title: 'Maximum XOR of Two Numbers', difficulty: 'medium', platform: 'LeetCode', pattern: 'Bitmasking', estimatedTime: 35, link: 'https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/', worldId: 18, patternId: 'w18-bitmask' },
        ],
      },
    ],
  },
  {
    id: 19,
    name: 'Dynamic Programming Galaxy',
    subtitle: 'Cosmos of optimal substructure',
    description: 'The DP Galaxy spans across time itself. Master the art of breaking problems into overlapping subproblems.',
    icon: '🌌',
    color: '#8b5cf6',
    bgGradient: 'from-violet-900/40 to-purple-800/20',
    boss: 'Time Weaver',
    bossDescription: 'A cosmic entity that weaves the fabric of optimal solutions. Only mastery of all DP patterns will prevail.',
    position: { x: 75, y: 55 },
    patterns: [
      {
        id: 'w19-1d',
        name: '1D Dynamic Programming',
        description: 'Classic 1D DP problems with single-variable states.',
        worldId: 19,
        problems: [
          { id: 'p19-1', title: 'Climbing Stairs', difficulty: 'easy', platform: 'LeetCode', pattern: '1D Dynamic Programming', estimatedTime: 15, link: 'https://leetcode.com/problems/climbing-stairs/', worldId: 19, patternId: 'w19-1d' },
          { id: 'p19-2', title: 'House Robber', difficulty: 'medium', platform: 'LeetCode', pattern: '1D Dynamic Programming', estimatedTime: 25, link: 'https://leetcode.com/problems/house-robber/', worldId: 19, patternId: 'w19-1d' },
          { id: 'p19-3', title: 'Word Break', difficulty: 'medium', platform: 'LeetCode', pattern: '1D Dynamic Programming', estimatedTime: 30, link: 'https://leetcode.com/problems/word-break/', worldId: 19, patternId: 'w19-1d' },
        ],
      },
      {
        id: 'w19-2d',
        name: '2D Dynamic Programming',
        description: 'DP on grids and matrices with two-variable states.',
        worldId: 19,
        problems: [
          { id: 'p19-4', title: 'Unique Paths', difficulty: 'medium', platform: 'LeetCode', pattern: '2D Dynamic Programming', estimatedTime: 20, link: 'https://leetcode.com/problems/unique-paths/', worldId: 19, patternId: 'w19-2d' },
          { id: 'p19-5', title: 'Longest Common Subsequence', difficulty: 'medium', platform: 'LeetCode', pattern: '2D Dynamic Programming', estimatedTime: 30, link: 'https://leetcode.com/problems/longest-common-subsequence/', worldId: 19, patternId: 'w19-2d' },
          { id: 'p19-6', title: 'Edit Distance', difficulty: 'hard', platform: 'LeetCode', pattern: '2D Dynamic Programming', estimatedTime: 45, link: 'https://leetcode.com/problems/edit-distance/', worldId: 19, patternId: 'w19-2d' },
        ],
      },
      {
        id: 'w19-knapsack',
        name: 'Knapsack Patterns',
        description: '0/1 Knapsack, unbounded knapsack, and their variations.',
        worldId: 19,
        problems: [
          { id: 'p19-7', title: 'Partition Equal Subset Sum', difficulty: 'medium', platform: 'LeetCode', pattern: 'Knapsack Patterns', estimatedTime: 35, link: 'https://leetcode.com/problems/partition-equal-subset-sum/', worldId: 19, patternId: 'w19-knapsack' },
          { id: 'p19-8', title: 'Coin Change', difficulty: 'medium', platform: 'LeetCode', pattern: 'Knapsack Patterns', estimatedTime: 30, link: 'https://leetcode.com/problems/coin-change/', worldId: 19, patternId: 'w19-knapsack' },
          { id: 'p19-9', title: 'Target Sum', difficulty: 'medium', platform: 'LeetCode', pattern: 'Knapsack Patterns', estimatedTime: 30, link: 'https://leetcode.com/problems/target-sum/', worldId: 19, patternId: 'w19-knapsack' },
        ],
      },
    ],
  },
  {
    id: 20,
    name: 'Advanced Algorithms Realm',
    subtitle: 'Dominion of the elite',
    description: 'The realm of advanced warriors. Segment Trees, String matching, Mo\'s Algorithm — elite techniques for elite problems.',
    icon: '🔮',
    color: '#06b6d4',
    bgGradient: 'from-cyan-900/40 to-sky-800/20',
    boss: 'Algorithm Overlord',
    bossDescription: 'The supreme overlord of algorithmic complexity. Only those wielding Segment Trees and advanced string algorithms may challenge it.',
    position: { x: 88, y: 48 },
    patterns: [
      {
        id: 'w20-segtree',
        name: 'Segment Tree & Fenwick Tree',
        description: 'Advanced range query data structures for dynamic arrays.',
        worldId: 20,
        problems: [
          { id: 'p20-1', title: 'Range Sum Query - Mutable', difficulty: 'medium', platform: 'LeetCode', pattern: 'Segment Tree & Fenwick Tree', estimatedTime: 40, link: 'https://leetcode.com/problems/range-sum-query-mutable/', worldId: 20, patternId: 'w20-segtree' },
          { id: 'p20-2', title: 'Count of Smaller Numbers After Self', difficulty: 'hard', platform: 'LeetCode', pattern: 'Segment Tree & Fenwick Tree', estimatedTime: 55, link: 'https://leetcode.com/problems/count-of-smaller-numbers-after-self/', worldId: 20, patternId: 'w20-segtree' },
        ],
      },
      {
        id: 'w20-strings',
        name: 'Advanced String Algorithms',
        description: 'KMP, Rabin-Karp, Z-Algorithm, Manacher for pattern matching.',
        worldId: 20,
        problems: [
          { id: 'p20-3', title: 'Find the Index of the First Occurrence', difficulty: 'easy', platform: 'LeetCode', pattern: 'Advanced String Algorithms', estimatedTime: 20, link: 'https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string/', worldId: 20, patternId: 'w20-strings' },
          { id: 'p20-4', title: 'Longest Palindromic Substring', difficulty: 'medium', platform: 'LeetCode', pattern: 'Advanced String Algorithms', estimatedTime: 35, link: 'https://leetcode.com/problems/longest-palindromic-substring/', worldId: 20, patternId: 'w20-strings' },
          { id: 'p20-5', title: 'Shortest Palindrome', difficulty: 'hard', platform: 'LeetCode', pattern: 'Advanced String Algorithms', estimatedTime: 55, link: 'https://leetcode.com/problems/shortest-palindrome/', worldId: 20, patternId: 'w20-strings' },
        ],
      },
    ],
  },
  {
    id: 21,
    name: 'Competitive Programming Universe',
    subtitle: 'The final frontier',
    description: 'The ultimate test. Number Theory, Combinatorics, Advanced Graphs, and Competitive DP. Achieve legendary status.',
    icon: '🏆',
    color: '#f59e0b',
    bgGradient: 'from-amber-900/40 to-orange-800/20',
    boss: 'Cosmic Judge',
    bossDescription: 'The final cosmic entity that judges all algorithmic knowledge. Defeat it to ascend to Algorithm Emperor.',
    position: { x: 92, y: 62 },
    patterns: [
      {
        id: 'w21-numtheory',
        name: 'Number Theory',
        description: 'Sieve of Eratosthenes, modular arithmetic, and prime factorization.',
        worldId: 21,
        problems: [
          { id: 'p21-1', title: 'Count Primes', difficulty: 'medium', platform: 'LeetCode', pattern: 'Number Theory', estimatedTime: 25, link: 'https://leetcode.com/problems/count-primes/', worldId: 21, patternId: 'w21-numtheory' },
          { id: 'p21-2', title: 'Ugly Number II', difficulty: 'medium', platform: 'LeetCode', pattern: 'Number Theory', estimatedTime: 30, link: 'https://leetcode.com/problems/ugly-number-ii/', worldId: 21, patternId: 'w21-numtheory' },
          { id: 'p21-3', title: 'Super Ugly Number', difficulty: 'medium', platform: 'LeetCode', pattern: 'Number Theory', estimatedTime: 35, link: 'https://leetcode.com/problems/super-ugly-number/', worldId: 21, patternId: 'w21-numtheory' },
        ],
      },
      {
        id: 'w21-combinatorics',
        name: 'Combinatorics',
        description: 'Counting, permutations, combinations, and Pascal\'s triangle.',
        worldId: 21,
        problems: [
          { id: 'p21-4', title: "Pascal's Triangle", difficulty: 'easy', platform: 'LeetCode', pattern: 'Combinatorics', estimatedTime: 15, link: "https://leetcode.com/problems/pascals-triangle/", worldId: 21, patternId: 'w21-combinatorics' },
          { id: 'p21-5', title: 'Unique Paths', difficulty: 'medium', platform: 'LeetCode', pattern: 'Combinatorics', estimatedTime: 20, link: 'https://leetcode.com/problems/unique-paths/', worldId: 21, patternId: 'w21-combinatorics' },
          { id: 'p21-6', title: 'K-th Smallest in Lexicographical Order', difficulty: 'hard', platform: 'LeetCode', pattern: 'Combinatorics', estimatedTime: 60, link: 'https://leetcode.com/problems/k-th-smallest-in-lexicographical-order/', worldId: 21, patternId: 'w21-combinatorics' },
        ],
      },
    ],
  },
];
